SkyCommerce.Loja/SkyCommerce.Site/Models/CheckoutViewModel.cs
using SkyCommerce.Data.Util;
using SkyCommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using SkyCommerce.ViewObjects;

namespace SkyCommerce.Site.Models
{
    public class CheckoutViewModel
    {
        public IEnumerable<Endereco> EnderecosUsuario { get; set; }

        public bool UtilizarEnderecoCadastrado { get; set; }
        public string NomeEnderecoCadastrado { get; set; }
        public Endereco EnderecoEntrega { get; set; }
        public bool EnderecoPagamentoMesmoEntrega { get; set; }
        public Endereco EnderecoCobranca { get; set; }
        public TipoPagamento TipoPagamento { get; set; }
        public bool ConcordouComTermosECondicoes { get; set; }
        public CartaoCredito CartaoCredito { get; set; }
        public Carrinho Carrinho { get; set; }
        public string Comentario { get; set; }
        public string Erro { get; set; }
        public IEnumerable<Frete> OpcoesFrete { get; set; }

        public Pedido GerarPedido(Carrinho carrinho, IEnumerable<Endereco> enderecos)
        {
            if (!ConcordouComTermosECondicoes)
                return null;

            if (UtilizarEnderecoCadastrado)
                EnderecoEntrega = enderecos.First(f => string.Equals(f.NomeEndereco.ToLower(), NomeEnderecoCadastrado.ToLower(), StringComparison.Ordinal));

            if (EnderecoPagamentoMesmoEntrega)
            {
                var novoEndereco = new Endereco();
                novoEndereco.ShallowCopyTo(EnderecoEntrega);
                EnderecoCobranca = novoEndereco;

            }
            if (Carrinho.TotalProdutos > 200)
                carrinho.Frete = new Frete() { Modalidade = "Gratis", Descricao = "Gratuito acima de R$200", Valor = 0 };

            return new Pedido(Carrinho.Frete, EnderecoCobranca, EnderecoEntrega, CartaoCredito, TipoPagamento, carrinho, Comentario);
        }

        public bool IsValid()
        {
            return ConcordouComTermosECondicoes;
        }
    }
}

SkyCommerce.Loja/SkyCommerce.Site/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using SkyCommerce.ViewObjects;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

namespace SkyCommerce.Site.Controllers
{
    [Route("catalogo")]
    public class CatalogoController : Controller
    {
        private readonly IProdutoStore _produtoStore;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IFreteService _freteService;
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaStore _categoriaStore;
        private readonly IMarcaStore _marcaStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CatalogoController(
            IProdutoStore produtoStore,
            IGeoposicaoService geoposicaoService,
            IFreteService freteService,
            IProdutoService produtoService,
            ICategoriaStore categoriaStore,
            IMarcaStore marcaStore,
            IHttpContextAccessor httpContextAccessor
            )
        {
            _produtoStore = produtoStore;
            _geoposicaoService = geoposicaoService;
            _freteService = freteService;
            _produtoService = produtoService;
            _categoriaStore = categoriaStore;
            _marcaStore = marcaStore;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Route("{produto}")]
        public async Task<IActionResult> Detalhes(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            var produtosRelacionados = await _produtoStore.ObterPorCategoria(produtoDetails.Categorias.FirstOrDefault());

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");

            var frete = await _freteService.ObterModalidades(at);

            return View(new ProdutoDetalhesViewModel()
            {
                Produto = produtoDetails,
                ProdutosRelacionados = produtosRelacionados.Where(w => w.NomeUnico != produtoDetails.NomeUnico).Take(6),
                OpcoesFrete = frete,
            });
        }

        private async Task<string> GeolocalizarUsuario()
        {
            var posicaoDoGuerreiro = Request.Cookies["geoposicao"];
            if (posicaoDoGuerreiro == null)
            {
                var localizacaoDoUsuario = await _geoposicaoService.ObterLocalizacaoAtual();
                posicaoDoGuerreiro = localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude;
                Response.Cookies.Append("geoposicao", localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude);
            }

            return posicaoDoGuerreiro;
        }

        [Route("visualizar/{produto}")]
        public async Task<IActionResult> PreVisualizar(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            return PartialView("Produtos/_Visualizar", produtoDetails);
        }

        [Route("comentar/{produto}")]
        public async Task<IActionResult> Comentar(string produto, [FromForm] Avaliacao avaliacao)
        {
            avaliacao.ProdutoUrl = produto;
            avaliacao.Imagem = "/images/site/default-user.png";
            await _produtoService.Comentar(avaliacao);
            return RedirectToAction("Detalhes", new { produto });
        }


        [Route("marcas/{marca}")]
        public async Task<IActionResult> Marca(string marca, [FromQuery] PesquisarProdutoVo model)
        {
            model.Marca = marca;
            var marcaDetalhes = await _marcaStore.ObterPorNome(marca);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorMarca(model),
                ImagemCapa = marcaDetalhes?.Imagem,
                Titulo = marcaDetalhes?.Nome,
                SubTitulo = string.Empty,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

SkyCommerce.Loja/SkyCommerce.Site/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Authorize, Route("checkout")]
    public class CheckoutController : Controller
    {
        private readonly IEnderecoStore _enderecoStore;
        private readonly ICarrinhoStore _carrinhoStore;
        private readonly IFreteService _freteService;
        private readonly ICarrinhoService _carrinhoService;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IPedidoService _pedidoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CheckoutController(
            IEnderecoStore enderecoStore,
            ICarrinhoStore carrinhoStore,
            IFreteService freteService,
            ICarrinhoService carrinhoService,
            IGeoposicaoService geoposicaoService,
            IPedidoService pedidoService,
            IHttpContextAccessor httpContextAccessor)
        {
            _enderecoStore = enderecoStore;
            _carrinhoStore = carrinhoStore;
            _freteService = freteService;
            _carrinhoService = carrinhoService;
            _geoposicaoService = geoposicaoService;
            _pedidoService = pedidoService;
            _httpContextAccessor = httpContextAccessor;
        }

        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento()
        {
            var enderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }
            if (!carrinho.FreteSelecionado())
            {
                TempData["ERRO"] = "Selecione o frete";
                return RedirectToAction("Index");
            }
            var cartao = CartaoCredito.Obter().Generate();
            return View(new CheckoutViewModel()
            {
                EnderecosUsuario = enderecosUsuario,
                Carrinho = carrinho,
                CartaoCredito = cartao
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento(CheckoutViewModel model)
        {
            model.EnderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            model.Carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (model.Carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }
            if (!model.IsValid())
            {
                model.Erro = "Concorde com os termos";
                return View(model);
            }


            var pedido = model.GerarPedido(model.Carrinho, model.EnderecosUsuario);
            await _pedidoService.SalvarPedido(pedido, User.Identity.Name);

            await _carrinhoService.LimparCarrinho(User.Identity.Name);

            return View("ConfirmarPedido", pedido);
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var fretes = await _freteService.CalcularCarrinho(carrinho, await _geoposicaoService.GeolocalizarUsuario(), at);
            return View(new CheckoutViewModel()
            {
                OpcoesFrete = fretes,
                Carrinho = carrinho,
            });
        }
    }
}

SkyCommerce.Loja/SkyCommerce.Site/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Route("pedidos"), Authorize]
    public class PedidosController : Controller
    {
        private readonly IPedidoStore _pedidoStore;

        public PedidosController(IPedidoStore pedidoStore)
        {
            _pedidoStore = pedidoStore;
        }

        public async Task<IActionResult> Index()
        {
            var pedidos = await _pedidoStore.ListarPedidos(User.Identity.Name);
            return View(pedidos);
        }

        [Route("{identificador}")]
        public async Task<IActionResult> Detalhes(string identificador)
        {
            var pedido = await _pedidoStore.ObterPorIdentificador(identificador, User.Identity.Name);
            return View(pedido);
        }
    }
}

SkyCommerce.Loja/SkyCommerce.Site/Views/Checkout/ConfirmarPedido.cshtml
@model SkyCommerce.Models.Pedido
@{
    ViewData["Title"] = "Detalhes do pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container main-container headerOffset">
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
            <ul class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li><a href="category.html">Category</a></li>
                <li class="active"> Order</li>
            </ul>
        </div>
    </div>
    <!--/.row-->


    <div class="row">
        <div class="col-lg-9 ">
            <div class="row userInfo">

                <div class="thanxContent text-center">

                    <h1> Obrigado pela compra <a asp-controller="Pedidos" asp-action="Detalhes" asp-route-identificador="@Model.IdentificadorUnico">#@Model.IdentificadorUnico</a></h1>
                    <h4>O pagamento será processado. Avisaremos assim que for processado.</h4>

                </div>

                <div class="col-lg-7 col-center">
                    <h4></h4>

                    <div class="cartContent table-responsive  w100">
                        <table style="width: 100%" class="cartTable cartTableBorder">
                            <thead>
                                <tr class="CartProduct  cartTableHeader">
                                    <th colspan="3"> Produtos comprados</th>


                                    <th style="width: 15%"></th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Produtos)
                                {
                                    <tr class="CartProduct">
                                        <td class="CartProductThumb">
                                            <div>
                                                <a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico"><img alt="@item.Nome" src="@item.Imagem"></a>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="CartDescription">
                                                <h4><a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico">@item.Nome</a></h4>

                                                <div class="price"><span>@item.Valor.ToString("C")</span></div>
                                            </div>
                                        </td>

                                        <td class="prices">
                                            @item.Quantidade
                                        </td>
                                        <td class="price">@item.Total.ToString("C")</td>
                                    </tr>
                                }
                                @if (Model.Frete.Modalidade == "Gratis")
                                {
                                    <tr>
                                        <td colspan="4" class="price text-center"><span class="success">Entrega Gratis</span></td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td></td>
                                        <td class="CartDescription">Frete - @Model.Frete.Modalidade</td>
                                        <td class="CartDescription">@Model.Frete.Descricao</td>
                                        <td class="price">@Model.Frete.Valor.ToString("C")</td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <!--/row end-->

        </div>

        <!--/rightSidebar-->

    </div>
    <!--/row-->

    <div style="clear:both"></div>
</div>